name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: bash ./configure
      
    - name: Build
      run: make
      
    - name: Gzip
      run: |
        mkdir hello-word
        cp hello hello-word
        tar czvf hello-word.tar.gz hello-word
    
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with: 
        args: hello-word.tar.gz application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
      

