name: C/C++ CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: bash ./configure
      
    - name: Build
      run: make
      
    - name: Gzip
      run: |
        mkdir hello-word
        cp hello hello-word
        tar czf hello-word.tar.gz hello-word
        
    - name: Create releas
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
      with:
        tag_name: v${{ github.run_number }}
        release_name:  Release V${{ github.run_name }}  
    
    - name: Upload to release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: hello-word.tar.gz
        asset_name: hello-v${{ github.run_number }}.tar.gz
        asset_content_type: application/tar+gzip
      
      

